# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        # 👇 Runs yarn in ./frontend
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken:  ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
#           projectToken
          # 👇 Runs Chromatic CLI in ./frontend
#           workingDir: package
#           projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
